version: '3.8'

services:
  frontend:
    container_name: menu-planner-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - go
    volumes:
      - type: bind
        source: ./frontend/app
        target: /usr/src/app

  go:
    container_name: menu-planner-go
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: go run cmd/main.go
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/app
        target: /go/src

  db:
    container_name: menu-planner-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - type: volume
        source: mysql_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/initdb.d
        target: /docker-entrypoint-initdb.d

volumes:
  mysql_volume:
    name: menu-planner-volume
